type
  TRSProcedure = RSCommon.TRSProcedure;
  TRSWndProcEvent = RSCommon.TRSWndProcEvent;
  TRSCreateParamsEvent = RSCommon.TRSCreateParamsEvent;
  TRSControlState = RSCommon.TRSControlState;

const
  RScsDisabled = RSCommon.RScsDisabled;
  RScsMouseIn = RSCommon.RScsMouseIn;
  RScsFocused = RSCommon.RScsFocused;
  RScsMouseDown = RSCommon.RScsMouseDown;
  RScsSpaceDown = RSCommon.RScsSpaceDown;

